version: "3"
services:
  dbserver:
    image: mysql:8.0
    container_name: lumos-image-mysql
    build: ./infra/mysql/
    environment:
      MYSQL_DATABASE: lumos_image_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      # MySQLの設定ファイル
      - ./infra/mysql/config:/etc/mysql/conf.d
      # 起動スクリプト
      - ./infra/mysql/initdb:/docker-entrypoint-initdb.d
  zookeeper-server:
    image: "bitnami/zookeeper:3.7.1"
    depends_on:
      - dbserver
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: "bitnami/kafka:3.4.0"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  backend-wrapper:
    image: lumos-image-backend-wrapper
    container_name: lumos-image-backend-wrapper
    depends_on:
      - kafka-server
    build: ./back-end/wrapper/
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  backend-image-saver:
    image: lumos-image-backend-image-saver
    container_name: lumos-image-backend-image-saver
    depends_on:
      - backend-wrapper
    build: ./back-end/image-saver/
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - shared_data:/storage
  backend-data-downloader:
    image: lumos-image-backend-data-downloader
    container_name: lumos-image-backend-data-downloader
    depends_on:
      - backend-image-saver
    build: ./back-end/data-downloader/
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - shared_data:/storage
  frontend:
    image: lumos-image-frontend
    container_name: lumos-image-frontend
    build: ./front-end/
    depends_on:
      - backend-data-downloader
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

volumes:
  shared_data:
